services:
  - type: web
    name: rapportini
    runtime: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        sync: false
      - key: ODOO_URL
        sync: false
      - key: ODOO_DB
        sync: false
      - key: ODOO_USERNAME
        sync: false
      - key: ODOO_PASSWORD
        sync: false
